// This file is automatically generated. Do not modify it manually.
// For more information, see https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
export const firebaseConfig = {
  apiKey: "TODO: YOUR API KEY",
  authDomain: "TODO: YOUR AUTH DOMAIN",
  projectId: "TODO: YOUR PROJECT ID",
  storageBucket: "TODO: YOUR STORAGE BUCKET",
  messagingSenderId: "TODO: YOUR MESSAGING SENDER ID",
  appId: "TODO: YOUR APP ID",
  measurementId: "TODO: YOUR MEASUREMENT ID",
};
